### ISSUE TITLE
Publish to f-droid or provide some nice description with screenshots

### ISSUE THREAD

**Issue by dumblob** [quarck/SmartNotify#1]
Hi, I just discovered this app and browsing the folder structure made an impression of a thoroughly thought-out architecture meaning it is probably pretty polished non-trivial app somewhat related to calendar/task/notification ecosystem.

Before diving into the sources, could you maybe write a summary and/or description and provide some pictures/screenshots to showcase what is this app about?

Thanks!

---

Also thanks for CalendarNotification(NG) app(s) which is the reason why I came across this repo.

Btw. do you have any write-up with reasoning why you stopped maintaining the notification app? If people (including me) would send you enough money to rewrite it to use the lowest "allowed" SDK, would you consider it?

**Comment by quarck** [comment]
This is a long abandoned project, probably won't compile with the most recent SDK even
